EMCIE_HOME := "./cache"
SERVER_ADDRESS := env("SERVER_ADDRESS", "http://localhost:8000")

setup-cache:
  mkdir -p {{EMCIE_HOME}}
  cp _config.json {{EMCIE_HOME}}/config.json

server *args: setup-cache
  EMCIE_HOME={{EMCIE_HOME}} poetry run python bin/emcie-server run {{args}}

client *args:
  EMCIE_HOME={{EMCIE_HOME}} poetry run python bin/emcie -s {{SERVER_ADDRESS}} {{args}}

validate *args: setup-cache
  EMCIE_HOME={{EMCIE_HOME}} poetry run python bin/emcie-server check {{args}}
