set dotenv-load
set positional-arguments

EMCIE_HOME := "./cache"

setup-cache:
  mkdir -p {{EMCIE_HOME}}

@server *args: setup-cache
  EMCIE_HOME={{EMCIE_HOME}} poetry run emcie-server run {{args}}

@validate *args: setup-cache
  EMCIE_HOME={{EMCIE_HOME}} poetry run emcie-server check {{args}}


test-ci-initial:
  poetry run pytest -v --plan=initial --tap-combined --capture=tee-sys | tee testresults.log
