set dotenv-load
set positional-arguments

EMCIE_HOME := "./cache"

setup-cache:
  mkdir -p {{EMCIE_HOME}}

@server *args: setup-cache
  EMCIE_HOME={{EMCIE_HOME}} poetry run emcie-server run {{args}}

@validate *args: setup-cache
  EMCIE_HOME={{EMCIE_HOME}} poetry run emcie-server check {{args}}


test-ci-initial-server:
  mkdir -p logs 
  poetry run pytest -v --plan=initial --tap-combined --tap-outdir=logs --capture=tee-sys --junit-xml=logs/testresults.xml | tee logs/testresults.log
  EXIT1=${PIPESTATUS[0]}
  echo $EXIT1

test-ci-initial-sdk:
  cd ../sdk
  mkdir -p logs 
  poetry run pytest -v --plan=initial --tap-combined --tap-outdir=logs --capture=tee-sys --junit-xml=logs/testresults.xml | tee logs/testresults.log
  EXIT1=${PIPESTATUS[0]}
  echo $EXIT1

test: test-ci-initial-server test-ci-initial-sdk

